version: "3"
services:
  app:
    container_name: goosechase
    build: ./
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres,
      DATABASE_PORT: 5432
      DATABASE_NAME: goosechase-dev
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
  postgres:
    container_name: postgres
    image: postgres:14.8
    ports:
      - "5432:5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data
      # - ./src/repositories/migrations/_setup.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goosechase-dev
#   pgadmin:
#     container_name: pgadmin
#     image: dpage/pgadmin4:7.3
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@goosechase.com
#       PGADMIN_DEFAULT_PASSWORD: tendTheFlock
#       PGADMIN_LISTEN_PORT: 80
#     ports:
#       - "8080:80"
#     volumes:
#       - pgadmin-data:/var/lib/pgadmin
#     depends_on:
#       - postgres
volumes:
    postgres-data:
#     pgadmin-data: